name: janken_game
description: "神の手じゃんけんゲーム"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/button/
    - assets/images/default_profiles/
    - assets/images/effects/
    - assets/images/goddess/
    - assets/images/icon/
    - assets/images/logo/
    - assets/images/rank/
    - assets/sounds/
    - assets/sounds/BGM/
    - assets/sounds/Button/
    - assets/json/
    - assets/policy/
    - assets/tournament-info/
    - assets/tournament-info/image/
    - assets/fonts/
  
  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-VariableFont_wght.ttf
    - family: KosugiMaru
      fonts:
        - asset: assets/fonts/KosugiMaru-Regular.ttf
    - family: M PLUS 1p
      fonts:
        - asset: assets/fonts/MPLUS1p-Regular.ttf